### ISSUE TITLE
Training on ActivityNet using default setting, got error in "eval_utils.py": float division by zero

### ISSUE THREAD

**Issue by serenayj** [JonghwanMun/LGI4temporalgrounding#4]
Hi, 

When I trained on activityNet using default setting, I got the error in eval_utils.py:
`
Write json file in results/anet/tgn_lgi/LGI/predictions/Train/epoch055.json
Traceback (most recent call last):
  File "src/experiment/train.py", line 124, in <module>
    train(config)
  File "src/experiment/train.py", line 107, in train
    net.save_results("epoch{:03d}".format(epoch), mode="Train")
  File "/home/LGI4temporalgrounding/src/model/LGI.py", line 215, in save_results
    self.results["predictions"], self.results["gts"])
  File "/home/LGI4temporalgrounding/src/utils/eval_utils.py", line 98, in eval
    correct, _ = self.eval_instance(pred, gt, topk=1)
  File "/home/LGI4temporalgrounding/src/utils/eval_utils.py", line 57, in eval_instance
    cur_tiou = compute_tiou(loc, gt)
  File "/home/LGI4temporalgrounding/src/utils/eval_utils.py", line 7, in compute_tiou
    return float(intersection) / union
ZeroDivisionError: float division by zero
`
Any idea on how to fix it?

**Comment by JonghwanMun** [comment]
I think, the value of union between prediction and GT can not be zero if any one of two is correct.
Note that although prediction would be wrong (i.e., start < end), GT should be correct and there should be no error.
Anyway, in such case, you can avoid it by adding the following condition statement `if union <= 0: return 0` before `return` statement.
